apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: object-auditor-webhook-cfg
  namespace: webhook-example
  labels:
    app: object-auditor
webhooks:
  - name: object-auditor.agreene.me
    clientConfig:
      service:
        name: object-auditor-webhook-svc
        namespace: webhook-example
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1EVXlOekUxTkRNeU4xb1hEVEk1TURVeU5URTFORE15TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBUFFVCnNheWNCRWJ3QUZqZkthSUptSU04MFBWZHVla3FoVWJabGdWNGkzdG9SMDJRVkFMdU5TUmR5VDJ5OEg2SHdsajAKRkgrQVAxUmh0bFJjcWthT1FGOEo3YlZtLzlOR3ZIK2VYL1dpM0l4b0tOam8xbmprT0RzNXFMWENtYW9BZ003VQp0Q08wOFRMS0ljaVF3RkZCbG9Fb3h0WlV6aXdMMzFJQkVpS096VmVpY2RHbUJaR2hrN3I4a2xtZ01uNWxLNDRBClZWL3liSEtpMlFFRnFiV1o3TnA3MHVucS93M0hoTE9xYWo4Vkd1dTI5RVFLZklrSEpBQld2QUVCNFg4SCtUSXQKV2ZkZmVEWTc5Tnh0cEpOZ09rT0tiUEJBRW5YWCtxTzdTVlB5YVBVWnlMWUpXUk9jYkpkQWtqR2ZNbmFrUmp0cgp2OFZGVVBxMmFzZW1LV0RsK2RjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFESTdIV1dqMno4T0FSaGZEWWZjenliTVFaazNTZ21CVWxzdDEwQ2FwWm1UOHVUOWRVdApYNU5xYnBabWowRVA0bW4wUEFhanJPOXNyWms4bVAra1lvZVR0dllvUURhdGYxSnl6d1g5cnhkY1RjNkFVTmZSCmQwcXB6T2h5andndkdicXI2a2ZCQmRTWXNPeEIyYWxHWWpkUk5lTjJkSFJQanFvVGFaVVp3QVRtaTFWUXRCdmMKdTRNeFpSVEJwUFRybytTbW5CUk1TMXlJQWRubzc2Zzg4S3hlM29NYXFHUnp0WCttSUwzcHJRRi9SVUtiV2FpRQozOHBpdkg0dGJ3Z25QU1IxVFE5U3I1UWpSQkdhbktpQXcyRHpUZDNmS1l2TFJaeTZ4alJ1YjA2aURxQUswcTM1CnM0NDgrQ0I3MGtXUERzMjZlUmhjQmI1Tm1hYlkrL29TWDBNYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["configmaps"]
    namespaceSelector:
      matchLabels:
        object-auditing: "enabled"
